import { useRef } from 'react';

const createUID = (): string => {
  return `_${Math.random().toString(36).slice(2, 11)}`;
};

/**
 * Generate unique identifier that is stable across renders.
 * @example const stableUID = useUID();
 * @returns uid:: The same autogenerated UID between renders.
 */
const useUID = (): string => {
  return useRef<string>(createUID()).current;
};

export default useUID;
